linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - gocyclo
    - gocritic
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: scanner2
      linters:
        - unused

linters-settings:
  gocritic:
    disable-all: true
    enabled-checks:
      - deprecatedComment
  govet:
    enable:
      - nilness
  gosec:
    excludes:
      - G501
      - G401
      - G505
